---
- hosts: all
  become: yes
  max_fail_percentage: 0 # 0 tolerance on failures, this is necessary to ensure max uptime https://docs.ansible.com/ansible/latest/user_guide/playbooks_delegation.html#maximum-failure-percentage
  vars_files:
  - ./vars/vars.yaml
  
  roles:
  - ha-os-pdc-upgrade