---
- name: Create validator wallet
  command: /home/{{ prysm_user }}/go/bin/ethdo wallet create --wallet="{{ validator_wallet_name }}" --type="{{ validator_wallet_type }}" --walletpassphrase="{{ validator_wallet_password }}"
