---
- name: Unlock geth account
  shell: "docker exec -it {{ geth_container_name }} geth attach {{ geth_connection }} --exec=\"personal.unlockAccount('{{ geth_account }}','{{ geth_account_password }}',36000)\""
  register: unlock_result

- name: Check unlock
  fail:
    msg: "Couldn't unlock account! Result: {{ unlock_result.stdout }}"
  when: unlock_result.stdout | regex_replace('\x1B\[([0-9]{1,2}(;[0-9]{1,2})?)?[mGK]', '') != "true"

- name: Gather deposit data
  command: "cat /home/{{prysm_user}}/depositdata"
  register: deposit_data

- name: Funding validators
  include_tasks: send-funds.yaml
  with_items: "{{ deposit_data.stdout.splitlines() }}"
