---
- name: Gather account names
  command: /home/{{ prysm_user }}/go/bin/ethdo wallet accounts --wallet="{{ validator_wallet_name }}"
  register: valiator_accounts
  
- name: Create file
  file:
    path: /home/{{ prysm_user }}/keystoreWallet.json
    state: touch

- name: Prepare beginning of file's content (json)
  lineinfile:
    path: /home/{{ prysm_user }}/keystoreWallet.json
    line: >
           {
             "location": "/data",
             "accounts": [
             
- name: Appending validators' names
  lineinfile:
    path: /home/{{ prysm_user }}/keystoreWallet.json
    line: "{% if validator_idx > 0 %},{% endif %}\"{{ validator_wallet_name}}/{{ item }}\""
  with_items: "{{ valiator_accounts.stdout.splitlines() }}"
  loop_control:
    index_var: validator_idx

- name: Prepare password list
  lineinfile:
    path: /home/{{ prysm_user }}/keystoreWallet.json
    line: "],\"passphrases\": ["

- name: Appending validators' passwords
  lineinfile:
    path: /home/{{ prysm_user }}/keystoreWallet.json
    regexp: "^ no this line doesnt exist"
    line: "{% if validator_idx > 0 %},{% endif %}\"{{ validator_accounts_password }}\""
  with_items: "{{ valiator_accounts.stdout.splitlines() }}"
  loop_control:
    index_var: validator_idx

- name: Finish file's content (json)
  lineinfile:
    path: /home/{{ prysm_user }}/keystoreWallet.json
    line: "]}"

- name: Put keystore into place (move file)
  command: mv /home/{{ prysm_user }}/keystoreWallet.json {{ prysm_install_path }}/validator/keystoreWallet.json